-include ../Makefile

linear_search: ## run linear_search
	g++ linear_search.cpp
	echo '3 7 1 7 5' | ./a.out
	echo '3 7 1 8 5' | ./a.out

min_linear_search: ## run min_linear_search
	g++ min_linear_search.cpp
	echo '3 9 7 5' | ./a.out
	echo '3 5 3 8' | ./a.out

pair_linear_search: ## run pair_linear_search
	g++ pair_linear_search.cpp
	echo '3 10 8 5 4 4 1 9' | ./a.out
