-include ../Makefile

sum: ## run sum
	g++ sum.cpp
	./a.out

euclid: ## run euclid
	g++ euclid.cpp
	./a.out

fibonacci: ## run fibonacci
	g++ fibonacci.cpp
	./a.out

for: ## run for
	g++ for.cpp
	./a.out

memo: ## run memo
	g++ memo.cpp
	./a.out

subsum: ## run subsum
	g++ subsum.cpp
	echo '5 10 1 2 4 5 11' | ./a.out

frog: ## run frog
	g++ frog.cpp
	echo '7 2 9 4 5 1 6 10' | ./a.out

pull: ## run pull
	g++ pull.cpp
	echo '7 2 9 4 5 1 6 10' | ./a.out

push: ## run push
	g++ push.cpp
	echo '7 2 9 4 5 1 6 10' | ./a.out
