-include ../Makefile

sum: ## run sum
	g++ sum.cpp
	./a.out

euclid: ## run euclid
	g++ euclid.cpp
	./a.out

fibonacci: ## run fibonacci
	g++ fibonacci.cpp
	./a.out

for: ## run for
	g++ for.cpp
	./a.out
