-include ../Makefile

binary_search: ## run binary_search
	g++ -std=c++11 binary_search.cpp
	./a.out

age: ## run age
	g++ -std=c++11 age.cpp
	./a.out

pair: ## run pair
	g++ -std=c++11 pair.cpp
	echo '3 10 8 5 4 4 1 9' | ./a.out
