-include ../Makefile

frog: ## run frog
	g++ frog.cpp
	echo '7 2 9 4 5 1 6 10' | ./a.out

pull: ## run pull
	g++ pull.cpp
	echo '7 2 9 4 5 1 6 10' | ./a.out

push: ## run push
	g++ push.cpp
	echo '7 2 9 4 5 1 6 10' | ./a.out

rec_frog: ## run rec_frog
	g++ rec_frog.cpp
	echo '7 2 9 4 5 1 6 10' | ./a.out

knapsack: ## run knapsack
	g++ -std=c++11 knapsack.cpp
	echo '6 10 2 3 1 2 3 6 2 1 1 3 5 85' | ./a.out

edit: ## run edit
	g++ -std=c++11 edit.cpp
	echo 'logistic algorithm' | ./a.out

split: ## run split
	g++ -std=c++11 split.cpp
	echo '5 1 2 3 4 5 6 7 8 9 10' | ./a.out
