-include ../Makefile

coin: ## run coin
	g++ -std=c++11 coin.cpp
	echo '1234 5 5 5 5 5 5' | ./a.out

schedule: ## run schedule
	g++ -std=c++11 schedule.cpp
	echo '5 1 3 2 5 12 17 5 9 10 13' | ./a.out
